[package]
name = "skia"
version = "0.1.0"
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
cssparser = { version = "0.27", features = ["serde"] }
euclid = { version = "0.20", features = ["serde"] }
futures = { version = "0.3", features = ["default", "thread-pool"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
skia-safe = { version = "0.27" }
napi-rs = { version = "0.2", path = "../../../napi-rs/napi" }
once_cell = "1.3"

[build-dependencies]
napi-build = { version = "0.1", path = "../../../napi-rs/build" }
